name: Train Model

on:
  push:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - run: |
        pip install mlflow
        pip install pandas
        pip install numpy
        pip install scikit-learn

    - name: Run MLflow Project
      run: |
        echo "Root Folder"
        ls -la

        echo "MLProject Folder"
        ls -la MLProject

        cd MLProject
        mlflow run . --env-manager local